In [68]:
from google.colab import drive
import pandas as pd

In [69]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

#Metropolitan

In [70]:
a = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/Agrimonia/Nuts/Metropolitan.xlsx')
a.rename(columns = {'NUTS ID':'NUTS_ID'}, inplace = True)

a.head()

  NUTS_ID METRO (No/Yes) METRO CODE METRO LABEL
0   AL011              N        NaN         NaN
1   AL012              N        NaN         NaN
2   AL013              N        NaN         NaN
3   AL014              N        NaN         NaN
4   AL015              N        NaN         NaN

# Mountain regions

In [71]:
b = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/Agrimonia/Nuts/Mountain regions.xlsx')
b.head()

,NUTS_ID,NUTS_LABEL,CATEGORY CODE,CATEGORY LABEL
0,BE100,Arr. de Bruxelles-Capitale/Arr. Brussel-Hoofdstad,4.0,Other regions
1,BE211,Arr. Antwerpen,4.0,Other regions
2,BE212,Arr. Mechelen,4.0,Other regions
3,BE213,Arr. Turnhout,4.0,Other regions
4,BE223,Arr. Tongeren,4.0,Other regions

# Urban-rural

In [72]:
c = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/Agrimonia/Nuts/Urban-rural.xlsx')
c.head()

  NUTS_ID  URBAN-RURAL CATEGORY     URBAN-RURAL LABEL
0   AL011                    3.0  predominantly rural
1   AL012                    2.0         intermediate
2   AL013                    3.0  predominantly rural
3   AL014                    3.0  predominantly rural
4   AL015                    2.0         intermediate

# Join of the three tables

In [73]:
d = a.merge(b, how='inner', on='NUTS_ID')
print(a.shape)
print(b.shape)
print(d.shape)
d.head()

(1514, 4)
(1514, 4)
(1514, 7)

,NUTS_ID,METRO (No/Yes),METRO CODE,METRO LABEL,NUTS_LABEL,CATEGORY CODE,CATEGORY LABEL
0,AL011,N,NaN,NaN,Dibër,3.0,> 50 % of population and 50 % of surface are i...
1,AL012,N,NaN,NaN,Durrës,2.0,> 50 % of surface are in mountain areas
2,AL013,N,NaN,NaN,Kukës,3.0,> 50 % of population and 50 % of surface are i...
3,AL014,N,NaN,NaN,Lezhë,3.0,> 50 % of population and 50 % of surface are i...
4,AL015,N,NaN,NaN,Shkodër,4.0,Other regions

In [74]:
e = a.merge(c, how='inner', on='NUTS_ID')
print(a.shape)
print(c.shape)
print(e.shape)
e.head()

(1514, 4)
(1514, 3)
(1514, 6)

,NUTS_ID,METRO (No/Yes),METRO CODE,METRO LABEL,URBAN-RURAL CATEGORY,URBAN-RURAL LABEL
0,AL011,N,NaN,NaN,3.0,predominantly rural
1,AL012,N,NaN,NaN,2.0,intermediate
2,AL013,N,NaN,NaN,3.0,predominantly rural
3,AL014,N,NaN,NaN,3.0,predominantly rural
4,AL015,N,NaN,NaN,2.0,intermediate

In [75]:
f = d.merge(e, how='inner', on='NUTS_ID')
print(d.shape)
print(e.shape)
print(f.shape)
f.head()

(1514, 7)
(1514, 6)
(1514, 12)

,NUTS_ID,METRO (No/Yes)_x,METRO CODE_x,METRO LABEL_x,NUTS_LABEL,CATEGORY CODE,CATEGORY LABEL,METRO (No/Yes)_y,METRO CODE_y,METRO LABEL_y,URBAN-RURAL CATEGORY,URBAN-RURAL LABEL
0,AL011,N,NaN,NaN,Dibër,3.0,> 50 % of population and 50 % of surface are i...,N,NaN,NaN,3.0,predominantly rural
1,AL012,N,NaN,NaN,Durrës,2.0,> 50 % of surface are in mountain areas,N,NaN,NaN,2.0,intermediate
2,AL013,N,NaN,NaN,Kukës,3.0,> 50 % of population and 50 % of surface are i...,N,NaN,NaN,3.0,predominantly rural
3,AL014,N,NaN,NaN,Lezhë,3.0,> 50 % of population and 50 % of surface are i...,N,NaN,NaN,3.0,predominantly rural
4,AL015,N,NaN,NaN,Shkodër,4.0,Other regions,N,NaN,NaN,2.0,intermediate

# Save the result

In [76]:
f.to_csv('/content/drive/MyDrive/Colab Notebooks/Agrimonia/Nuts/resultNuts3.csv')